// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace wds.pink.fluffy
{
public static class Constants
{
        public const string leaderboard_longest_bouncers = "CgkI98bP5awNEAIQBw"; // <GPGSID>
        public const string achievement_cloud_hopper = "CgkI98bP5awNEAIQAg"; // <GPGSID>
        public const string achievement_air_fluffle = "CgkI98bP5awNEAIQBQ"; // <GPGSID>
        public const string achievement_apprentice_bouncer = "CgkI98bP5awNEAIQAQ"; // <GPGSID>
        public const string achievement_in_the_clounds = "CgkI98bP5awNEAIQAw"; // <GPGSID>
        public const string achievement_marshmallow = "CgkI98bP5awNEAIQBA"; // <GPGSID>

}
}
